const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_TO_CART = "REMOVE_TO_CART";
const FETCH_TO_PRODUCT ="FETCH_TO_PRODUCT";
const FETCH_TO_CART ="FETCH_TO_CART";

export {ADD_TO_CART,REMOVE_TO_CART,FETCH_TO_PRODUCT,FETCH_TO_CART};